// Generated by Wrangler by running `bun run cf-typegen`

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
	}
}

interface CloudflareBindings extends Cloudflare.Env {}
