name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ["1.2.23", "latest"]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build assets
        run: bun run css:build && bun run js:build

      - name: Run tests
        run: bun run test

      - name: Generate coverage
        if: matrix.bun-version == 'latest'
        run: bun run coverage

      - name: Upload coverage to Codecov
        if: matrix.bun-version == 'latest'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ./coverage/cobertura-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
